name: itsypad-ios
options:
  bundleIdPrefix: com.nickustinov
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: false

settings:
  base:
    DEVELOPMENT_TEAM: R892A93W42
    CODE_SIGN_STYLE: Automatic
    CODE_SIGN_IDENTITY: "Apple Development"

targets:
  Itsypad:
    type: application
    platform: iOS
    sources:
      - path: Sources
        excludes:
          - Info.plist
          - itsypad-ios.entitlements
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: Itsypad
        LSApplicationCategoryType: public.app-category.productivity
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        ITSAppUsesNonExemptEncryption: false
        UIBackgroundModes:
          - remote-notification
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nickustinov.itsypad
        PRODUCT_NAME: Itsypad
        PRODUCT_MODULE_NAME: ItsypadCore
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "103"
        CODE_SIGN_ENTITLEMENTS: Sources/itsypad-ios.entitlements
        SWIFT_VERSION: "5.9"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE: false
        INFOPLIST_KEY_CFBundleDisplayName: Itsypad
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.productivity

  ItsypadTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: Itsypad
    settings:
      base:
        SWIFT_VERSION: "5.9"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        GENERATE_INFOPLIST_FILE: true
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Itsypad.app/Itsypad"
        BUNDLE_LOADER: "$(TEST_HOST)"
